const data = [
    {
        "id": 1,
        "title": "iPhone 9",
        "price": 549,
        "rating": 4.69,
        "brand": "Apple",
    },
    {
        "id": 2,
        "title": "Galaxy S30",
        "price": 549,
        "rating": 4.69,
        "brand": "Samsung",
    },
    {
        "id": 3,
        "title": "Experia Z",
        "price": 549,
        "rating": 4.69,
        "brand": "Sony",
    },
    {
        "id": 4,
        "title": "Redmi 20",
        "price": 549,
        "rating": 4.69,
        "brand": "Xiaomi",
    },
    {
        "id": 5,
        "title": "One",
        "price": 549,
        "rating": 4.69,
        "brand": "OnePlus",
    },
    {
        "id": 6,
        "title": "G50",
        "price": 549,
        "rating": 4.69,
        "brand": "LG",
    },
    {
        "id": 7,
        "title": "Note 30",
        "price": 549,
        "rating": 4.69,
        "brand": "Samsung",
    },
    {
        "id": 8,
        "title": "A50",
        "price": 549,
        "rating": 4.69,
        "brand": "Samsung",
    },
    {
        "id": 9,
        "title": "iPhone 9 Plus",
        "price": 549,
        "rating": 4.69,
        "brand": "Apple",
    },
    {
        "id": 10,
        "title": "iPhone 9 Pro",
        "price": 549,
        "rating": 4.69,
        "brand": "Apple",
    },
    {
        "id": 11,
        "title": "iPhone 9 Plus Pro",
        "price": 549,
        "rating": 4.69,
        "brand": "Apple",
    },
    {
        "id": 12,
        "title": "P90",
        "price": 549,
        "rating": 4.69,
        "brand": "Huawei",
    }
]